### ISSUE TITLE
about the openpose results fed into the smpl-x model

### ISSUE THREAD

**Issue by huge123** [DirtyHarryLYL/DJ-RN#4]
Thanks for sharing the great work, but I meet some problems with the openpose results:
1. what are the formats/dimensions of the 2D parameters _theta_b^2D_,_theta_h_^2D, ..?  Are they the coordinates of the corresponding keypoints? And are there any conversions before feeding them into the smpl-x model ?
2.  could you provide the corresponding codes or instruction for running the step 4 in the data generation? **Run SMPLify-X on the dataset with the filtered pose.**
3.  this question may not be so relevant to this work. Is it possible to get the 3D joint locations from the smpl-x model?

**Comment by Foruck** [comment]
Thanks for using our code!

About Q1, I assume you are wondering about the dimensions of theta_b^3D, theta_h^3D, ... Here referring to the [orginial paper of SMPL-X](https://ps.is.tuebingen.mpg.de/uploads_file/attachment/attachment/497/SMPL-X.pdf):

>  The total number of model parameters in SMPL-X is 119: 75 for the global body rotation and { body, eyes , jaw } joints, 24 parameters for the lower dimensional hand pose PCA space, 10 for subject shape and 10 for the facial expression,

where theta_b^3D and theta_f^3D are corresponding to `the global body rotation and { body, eyes , jaw } joints`, theta_h^3D is corresponding to `the lower dimensional hand pose PCA space`, beta is corresponding to the `subject shape` and psi is corresponding to the `facial expression`. While in practical use, theta_b^3D is encoded to a lower dimension latent space by the VPoser proposed in the same paper, with size of 32. Therefore, all of them are not joint coordinates. And since SMPL-X has assembled the latent code decoding process, no conversions need to be done before feeding them to the model.

About Q2, like described in the [smplify-x instruction](https://github.com/vchoutas/smplify-x/blob/master/README.md#L38), you could run SMPLify-X on the dataset with filtered pose as:
```Shell
python smplifyx/main.py --config cfg_files/fit_smplx.yaml 
    --data_folder DATA_FOLDER # 
    --output_folder OUTPUT_FOLDER 
    --visualize="True/False"
    --model_folder MODEL_FOLDER
    --vposer_ckpt VPOSER_FOLDER
    --part_segm_fn smplx_parts_segm.pkl
```
where the DATA_FOLDER should contain two subfolders, images, where the images are located, and keypoints, where the filtered OpenPose output should be stored.

About Q3, it is possible, and there are multiple ways. The version of SMPLify-X that we used didn't save the 3D joint locations of the recovered body model. You could modify the SMPLify-X code to make it save the joint location, or you could use this function to extract the 3D joint location from the recovered `obj` file, where `J_regressor` is actually the files in the Step. 4 in the Installation section.
https://github.com/DirtyHarryLYL/DJ-RN/blob/4bfdf0cf11628cad682aeb4202d12d88c98abb19/script/generate_utils.py#L79

**Comment by huge123** [comment]
Thanks for the patient reply. I wonder if I understand it correctly: the inputs to the smpl-x model is the coordinates of the detected 2D keypoints, which will be automatically converted to the parameters of the 3D model e.g. theta_h^3D, theta_b^3D, etc. With the 3D parameters, we can get the corresponding mesh or the vertices from the smpl-x model.

**Comment by Foruck** [comment]
The inputs to **SMPLifiy-X** are the coordinates of the detected 2D keypoints, and **SMPLifiy-X** will perform the recovery and return the parameters of the **SMPL-X** 3D model e.g. theta_h^3D, theta_b^3D, etc. And the **SMPL-X** model takes the parameters as input and output the corresponding mesh and vertices, while the joints could also be fetched with the mesh and vertices.

**Comment by huge123** [comment]
Got it, thank you very much
