### ISSUE TITLE
Would you mind to provide 3d features extracted by SMPL-X?

### ISSUE THREAD

**Issue by xxxzhi** [DirtyHarryLYL/DJ-RN#5]
Hi, Thanks for your work. Since the project has used many 3D features extracted by SMPL-X, would you mind provide the features that you have extracted like 2d pose pickle file? I guess it would be easy to follow you work.

**Comment by Foruck** [comment]
Thanks for using our code! Due to the massive storage space the features could take up, currently generating the features on a local server following the steps that we provide is still preferred. And we are working on the journal version of this project, in which the whole model will become more concise and the storage will be tuned to fit the need of online sharing. We will make the newer version public ASAP.

**Comment by xxxzhi** [comment]
Ok, thanks. How many storage space it requires?

**Comment by Foruck** [comment]
The whole feature data occupies approximately 1TB. And here we provide [the original openpose result](https://drive.google.com/file/d/14QiZSMFLc5FOmkQEHgOY1_E0eM8-60UM/view?usp=sharing).

**Comment by xxxzhi** [comment]
Ok, thank u very much.
