### ISSUE TITLE
Not sure what does the result of generate_3D_obj_Neg.py is supposed to be as or why we run this script at all?

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#65]
Could you please explain in simple terms what you are trying to do with this script? I am a bit baffled on why in ends up in a result such as below or why we would need it?
![Screenshot from 2021-06-09 12-41-56](https://user-images.githubusercontent.com/76495162/121396214-23ffc300-c921-11eb-8e27-fa1dc59fe6dc.png)

This is while generate_3D_obj_GT.py creates the following 3D human-object mesh:
![Screenshot from 2021-06-09 12-38-00](https://user-images.githubusercontent.com/76495162/121396308-3bd74700-c921-11eb-86f4-5416f95710e9.png)

for the following image:
![HICO_train2015_00006346](https://user-images.githubusercontent.com/76495162/121396319-41cd2800-c921-11eb-881b-2cfcb1e68ab9.jpg)

**Comment by DirtyHarryLYL** [comment]
generate_3D_obj_Neg.py provides the negative training samples for our model, compared to the one generated by generate_3D_obj_GT.py ( generating positive samples), it is inaccurate because of the wrong object (this small ball is not interactive with this girl in "riding").
The ratio of pos : neg samples is 1:4.
