### ISSUE TITLE
Object Sphere Center

### ISSUE THREAD

**Issue by mansooreh1** [DirtyHarryLYL/DJ-RN#70]
Hello
How the center of the object sphere is determined?

**Comment by DirtyHarryLYL** [comment]
Please refer to the paper illustration and the [function](https://github.com/DirtyHarryLYL/DJ-RN/blob/7f362693f433d49e2fb5c0fc6216218d464c612b/script/generate_utils.py#L174).
For convenience, we directly provide the solutions to the geometry equations.
The depth estimation is bounded by the prior human-object relative depth relations labeled by humans (min-z, max-z), e.g., for hold-cup, the cup would not be too far from the human.
![image](https://user-images.githubusercontent.com/13531138/131257487-c23dc8d0-368e-4b67-adaa-35307893e31b.png)

**Comment by mansooreh1** [comment]
I meant the center of the sphere, not its depth and radius

**Comment by mansooreh1** [comment]
How to get the optical center C?

**Comment by DirtyHarryLYL** [comment]
I meant the center of the sphere, not its depth and radius
--I meant x_o, y_o, z_o too. 
z_o is decided by the depth. The sphere is tangent to the two planes P1 and P2, then the sphere center will fall on the P_ABC including x_o and y_o. x_o and y_o are easy to locate because we can find the clues from the 2d boxes and C locations. But depth is hard, so we also define a boundary for it from human priors.

Camera parameters come from the SMPLify-x, like focal length, C.
